[engine]
rate = 20                                   # 速率
duration = "20s"                            # 持续时间
cap = 4                                     # 客户端虚拟机数量
instant=3                                   # 每个批次发的交易数
wait="0s"                                   # 获取cap最大等待时间

[client]
script = "benchmark/fisco-bcos3/invoke/script.lua"     # 脚本
type = "fisco-bcos"                                        # 区块链类型
contract = "benchmark/fisco-bcos3/invoke/contract"     # 合约目录路径
config = "benchmark/fisco-bcos3/invoke/fisco-bcos3"            # 区块链SDK配置路径
plugin = "./fisco-bcos3.so"                                 # 插件路径
args = ["1.0"]                                      # 合约参数路径

[client.options] # 客户端选项

[recorder.log]
dump=false
dir="./logs"
level="debug"

[recorder.csv]
dir="./csv"





